#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ifaddr
Version  : 0.1.5
Release  : 3
URL      : https://files.pythonhosted.org/packages/7f/bd/08d26d3a31b6cd0e1a771f3d322bba3f90b118ae7420254f717e8b3b95b1/ifaddr-0.1.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/7f/bd/08d26d3a31b6cd0e1a771f3d322bba3f90b118ae7420254f717e8b3b95b1/ifaddr-0.1.5.tar.gz
Summary  : Enumerates all IP addresses on all network adapters of the system.
Group    : Development/Tools
License  : MIT
Requires: ifaddr-python = %{version}-%{release}
Requires: ifaddr-python3 = %{version}-%{release}
Requires: ipaddress
BuildRequires : buildreq-distutils3
BuildRequires : ipaddress

%description
ifaddr - Enumerate IP addresses on the local network adapters
        =============================================================
        
        `ifaddr` is a small Python library that allows you to find all the
        IP addresses of the computer. It is tested on **Linux**, **OS X**, and
        **Windows**.
        
        This library is open source and released under the MIT License.
        
        You can install it with `pip install ifaddr`. It doesn't need to
        compile anything, so there shouldn't be any surprises. Even on Windows.
        
        ----------------------
        Let's get going!
        ----------------------

%package python
Summary: python components for the ifaddr package.
Group: Default
Requires: ifaddr-python3 = %{version}-%{release}

%description python
python components for the ifaddr package.


%package python3
Summary: python3 components for the ifaddr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ifaddr package.


%prep
%setup -q -n ifaddr-0.1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543726725
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
